apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-book-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-book-api
  template:
    metadata:
      labels:
        app: my-book-api
    spec:
      containers:
      - name: my-book-api-container
        image: my-book-api-image:latest
        imagePullPolicy: Never 
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: my-book-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: my-book-api